# Generated by Django 4.2 on 2023-05-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Others', 'Others')], default='khalti', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
