# Generated by Django 4.2 on 2023-05-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_first_name_customer_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='username',
        ),
    ]
