# Generated by Django 4.1.1 on 2023-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Documentary', 'Dcoumentary'), ('Science Fiction', 'Science Fiction'), ('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Western', 'Western'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Romantic comedy', 'Romantic Comedy'), ('Crime Film', 'Crime Film'), ('Fantasy', 'Fantasy'), ('Film Noir', 'Film Noir'), ('War', 'War'), ('Experimental', 'Experimental'), ('Mystery', 'Mystery'), ('Biographical', 'Biographichal'), ('Dark Comedy', 'Dark Comedy'), ('Historical Film', 'Historical Film'), ('Short', 'Short'), ('Spy', 'Spy'), ('Musical', 'Musical')], max_length=50)),
                ('synopsis', models.TextField(blank=True, max_length=200)),
                ('posterurl', models.URLField(blank=True)),
            ],
        ),
    ]
